import 'angular';
import 'angular-animate';
import 'angular-ui-router';
import 'github:angular/bower-angular-messages';
import 'github:lodash/lodash';
import 'github:mgonto/restangular';
import 'github:angular-ui/bootstrap-bower';
import 'github:grevory/angular-local-storage';
import 'github:jeremypeters/ng-bs-animated-button';
